# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfe056dfb61c1ebd74a54098e7e4990ccbe13aa23cf01b34b193faa41994e22ad9d280c3ee3039f5e80e17a01d91997eed314a843fd38d8f498242f66987c1ab

test:
  secret_key_base: 93e18ff6216ff8a55961c9ef57060a3e23710fa2e844b5bbb8c7bbdd1ca913d0d17122656340c5dc59484cf9bd8e85c74033d20415d26fbb3b080e56cb06749f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
